##Random Forest Regression 

In [1]:
#Required Libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


In [2]:
#Loading the data set from drive 
dataset = pd.read_csv("/content/drive/MyDrive/Position_Salaries.csv")

In [3]:
dataset.head(10)

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [17]:
# Assigning data into x and y 
X = dataset.iloc[:,1:2].values
Y = dataset.iloc[:,2].values 

In [18]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
Y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [23]:
#Splitting the data into train and test 
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , Y , test_size= 0.1 , random_state=0)

## Feature scalling 
the process to scale the input feature for a model. Feature scalling may occure through two things  
#### Standardization and Normalization
### 1
### Normalization  
Normalization is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1. It is also known as Min-Max scaling.
### 2
#### Standardization 
is another scaling technique where the values are centered around the mean with a unit standard deviation. This means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation. (ie) in which mean is 0 and standard devation is 1.
The standard deviation is a statistic that measures the dispersion of a dataset relative to its mean. It is calculated as the square root of variance 

In [25]:
 # Feature Scaling 
 from sklearn.preprocessing import StandardScaler 

 # initiating the Scaler
 
 scaler_X = StandardScaler()

 #Scaling X train
x_train = scaler_X.fit_transform(x_train )

#Scaling X test 
x_test = scaler_X.fit_transform(x_test)


# Scalling Y 
scaler_Y = StandardScaler()

#Scaling y train
y_train  = scaler_Y.fit_transform(Y.reshape(-1, 1),y_train )

## Fitting the RandomForest Regressor

In [26]:
#Importing the reggresor 
from sklearn.ensemble import RandomForestRegressor 

# Intializing Regresor 

regressor = RandomForestRegressor(n_estimators = 10 , random_state = 0 ) # n_estimators : This is the number of trees you want to build before taking the maximum voting or averages of predictions
 
#fitting the regressor 
regressor.fit(X,Y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [30]:
y_pred = regressor.predict(y_test.reshape(-1,1) )

In [31]:
y_pred

array([850000.])